name: Run tests before mergin with 'main' branch
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and Test Docker Container
        run: |
          docker build -t cygnetops/react-test -f Dockerfile.dev .
          docker run -e CI=true cygnetops/react-test npm test
